window.PORTFOLIO_PROJECTS = [
    {
        id: 1,
        title: 'BidaBoss Inc.',
        description: 'A complete redesign of the BidaBoss Inc. e-commerce platform focused on improving user experience, visual consistency, and overall usability for all stakeholders, featuring a cleaner interface, enhanced navigation, and a more streamlined flow.',
        type: 'Website',
        kind: 'Professional Project',
        category: 'web',
        image: 'assets/img/Bidaboss.png',
        gallery: ['assets/img/bidaboss_1.png'],
        techStack: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
        keywords: ['Web', 'E-commerce', 'Responsive'],
        liveSite: 'https://bidaboss.ph'
    },
    {
        id: 10,
        title: 'DREAM',
        description: 'A sample mockup UI design requested by the client for DREAM — a front-end design concept for a wellness and beauty technology brand. The site explores product storytelling, ritual-focused layout, and promotional visuals using AI-generated images of their product. This is a concept presentation, not a production build.',
        type: 'UI Design Concept',
        kind: 'Client Project',
        category: 'web',
        image: 'assets/img/dream.png',
        gallery: ['assets/img/dream.png'],
        techStack: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Three.js'],
        keywords: ['Mockup', 'UI Concept', 'AI Visuals'],
        liveSite: 'https://dream-skincare.vercel.app'
    },
    {
        id: 2,
        title: 'Kings Skincare Website',
        description: 'A luxurious, premium-style skincare website designed specifically for men, featuring a clean and sophisticated layout that highlights product quality, ingredients, and brand identity while delivering a smooth and refined browsing experience.',
        type: 'Single Page Website',
        kind: 'Client Project',
        category: 'web',
        image: 'assets/img/kings.png',
        gallery: ['assets/img/kings_1.png'],
        techStack: ['HTML', 'CSS', 'JavaScript'],
        keywords: ['Luxurious', 'Premium', 'Gifting'],
        liveSite: 'https://stg-single-page-checkout.netlify.app/kings-skincare/'
    },
    {
        id: 3,
        title: 'iHome Speaker Website',
        description: 'A modern single-page product website showcasing a Bluetooth speaker with a focus on clean design, smooth user experience, and clear product highlights such as wireless connectivity, portability, and high-quality sound.',
        type: 'Single Page Website',
        kind: 'Client Project',
        category: 'web',
        image: 'assets/img/ihomes.png',
        gallery: ['assets/img/ihomes_1.png'],
        techStack: ['HTML', 'CSS', 'JavaScript'],
        keywords: ['Modern', 'Sleek', 'Immersive'],
        liveSite: 'https://stg-single-page-checkout.netlify.app/ihome-speaker/'
    },
    {
        id: 9,
        title: 'Arkitrio',
        description: 'A client website for an architecture studio that presents their practice, services, and project folio in a refined, spatial layout. It covers planning, architectural design, visualizations, interiors, and design + build — so visitors can explore the studio’s process and built work with the same considered feel as the spaces they create.',
        type: 'Website',
        kind: 'Client Project',
        category: 'web',
        image: 'assets/img/arkitrio.png',
        gallery: ['assets/img/arkitrio.png', 'assets/img/arkitrio_1.png', 'assets/img/arkitrio_2.png'],
        techStack: ['HTML', 'CSS', 'JavaScript'],
        keywords: ['Architecture', 'Studio', 'Spatial'],
        liveSite: 'https://arkitrio.netlify.app'
    },
    {
        id: 5,
        title: 'BidaBoss Supplier Management System',
        description: 'As Lead UI/UX Designer, I redesigned this existing supplier system at BidaBoss Inc. It supports vendor onboarding, product listings, inventory, purchase orders, and status tracking — designed to keep supplier operations clear, consistent, and easier to manage alongside the main platform.',
        type: 'Web App',
        kind: 'Professional Project',
        category: 'web',
        image: 'assets/img/Supplier_1.png',
        gallery: ['assets/img/Supplier_1.png', 'assets/img/Supplier_2.png', 'assets/img/Supplier_3.png', 'assets/img/Supplier_4.png', 'assets/img/Supplier_5.png', 'assets/img/Supplier_6.png'],
        techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'MySQL'],
        keywords: ['Suppliers', 'Operations', 'Dashboard'],
        liveSite: '#'
    },
    {
        id: 6,
        title: 'Warehouse Management System',
        description: 'As Lead UI/UX Designer, I redesigned this existing warehouse system at BidaBoss Inc. It is the core operations platform for catalog, orders, customers, and internal workflows, with a cleaner hierarchy, stronger consistency, and faster day-to-day use for admins and staff.',
        type: 'Web App',
        kind: 'Professional Project',
        category: 'web',
        image: 'assets/img/main_1.png',
        gallery: ['assets/img/main_1.png', 'assets/img/main_2.png'],
        techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'MySQL'],
        keywords: ['Operations', 'E-commerce', 'Admin'],
        liveSite: '#'
    },
    {
        id: 8,
        slug: 'bidaboss-app',
        title: 'BidaBoss Inc. Mobile App',
        description: 'I designed this mobile app while I was still an intern at BidaBoss Inc. It lets users browse products, manage orders, and stay connected to the platform on the go. I worked on the UI/UX and front-end so shopping and order tracking feel consistent with the web experience, just sized for the phone. You can download it on the Google Play Store — search “bidaboss.”',
        type: 'Mobile App',
        kind: 'Professional Project',
        category: 'mobile',
        image: 'assets/img/bidabossmobile_cover.png',
        gallery: ['assets/img/bidabossmobile_cover.png', 'assets/img/bidaapp_1.jpg', 'assets/img/bidaapp_2.jpg', 'assets/img/bidaapp_3.jpg', 'assets/img/bidaapp_4.jpg', 'assets/img/bidaapp_5.jpg', 'assets/img/bidaapp_6.jpg', 'assets/img/bidaapp_7.jpg', 'assets/img/bidaapp_8.jpg', 'assets/img/bidaapp_9.jpg', 'assets/img/bidaapp_10.jpg', 'assets/img/bidaapp_11.jpg'],
        techStack: ['Flutter', 'Dart', 'REST API'],
        keywords: ['Mobile', 'E-commerce', 'Orders'],
        liveSite: '#',
        video: 'assets/video/bidaboss-app.mp4',
        screenshots: ['assets/img/bidaapp_1.jpg', 'assets/img/bidaapp_2.jpg', 'assets/img/bidaapp_3.jpg', 'assets/img/bidaapp_4.jpg', 'assets/img/bidaapp_5.jpg', 'assets/img/bidaapp_6.jpg', 'assets/img/bidaapp_7.jpg', 'assets/img/bidaapp_8.jpg', 'assets/img/bidaapp_9.jpg', 'assets/img/bidaapp_10.jpg', 'assets/img/bidaapp_11.jpg']
    },
    {
        id: 7,
        slug: 'quiz-mania',
        title: 'Quiz Mania',
        description: 'A school project we built as college students to make reviewing easier. Take timed multiple-choice quizzes across a variety of general knowledge categories, or use it as a reviewer for upcoming tests by adding your own flashcards and creating your own question-and-answer sets. It is also a good reviewer partner.',
        type: 'Mobile App',
        kind: 'School Project',
        category: 'mobile',
        image: 'assets/img/quiz_cover.png',
        gallery: ['assets/img/quiz_cover.png', 'assets/img/quizmania_1.jpg', 'assets/img/quizmania_2.jpg', 'assets/img/quizmania_3.jpg', 'assets/img/quizmania_4.jpg', 'assets/img/quizmania_5.jpg', 'assets/img/quizmania_6.jpg', 'assets/img/quizmania_7.jpg'],
        techStack: ['Flutter', 'Dart', 'Firebase'],
        keywords: ['Mobile', 'Quiz', 'Reviewer'],
        liveSite: '#',
        video: 'assets/video/quiz-mania.mp4',
        screenshots: ['assets/img/quizmania_1.jpg', 'assets/img/quizmania_2.jpg', 'assets/img/quizmania_3.jpg', 'assets/img/quizmania_4.jpg', 'assets/img/quizmania_5.jpg', 'assets/img/quizmania_6.jpg', 'assets/img/quizmania_7.jpg']
    },
    {
        id: 4,
        slug: 'circlo',
        title: 'Circlo',
        description: 'This project is still in progress. Circlo is a private social app for real relationships — not a public feed. Users create isolated Circles for couples, family, or friends, then share memories, chat, plan events, keep calendars, and work on goals together inside that space only. Each Circle stays fully separate, with its own gallery, notes, tasks, and activities. I built the Flutter app and Laravel API foundation so every relationship can have its own calm, private home.',
        type: 'Mobile App',
        kind: 'Personal Project',
        category: 'mobile',
        status: 'In progress',
        image: 'assets/img/circlo_cover.png',
        gallery: ['assets/img/circlo_cover.png', 'assets/img/circlo_1.jpg', 'assets/img/circlo_2.jpg'],
        techStack: ['Flutter', 'Dart', 'Riverpod', 'Laravel', 'MySQL'],
        keywords: ['Mobile', 'Private Circles', 'Relationships'],
        liveSite: 'https://github.com/Ninixci4/Circlo',
        video: 'assets/video/circlo.mp4',
        screenshots: ['assets/img/circlo_1.jpg', 'assets/img/circlo_2.jpg']
    }
];
