window.PORTFOLIO_PROJECTS = [
    {
        id: 1,
        title: 'BidaBoss Inc.',
        description: 'A complete redesign of the Bidaboss e-commerce platform focused on improving user experience, visual consistency, and overall usability for all stakeholders, featuring a cleaner interface, enhanced navigation, and a more streamlined flow.',
        type: 'Website',
        category: 'web',
        image: 'assets/img/Bidaboss.png',
        gallery: ['assets/img/bidaboss_1.png', 'assets/img/bidaboss_2.png'],
        techStack: ['HTML', 'CSS', 'JavaScript', 'React', 'Node.js'],
        keywords: ['Web', 'E-commerce', 'Responsive'],
        liveSite: 'https://bidaboss.ph'
    },
    {
        id: 2,
        title: 'Kings Skincare Website',
        description: 'A luxurious, premium-style skincare website designed specifically for men, featuring a clean and sophisticated layout that highlights product quality, ingredients, and brand identity while delivering a smooth and refined browsing experience.',
        type: 'One-Page Website',
        category: 'web',
        image: 'assets/img/kings.png',
        gallery: ['assets/img/kings_1.png'],
        techStack: ['HTML', 'CSS', 'JavaScript'],
        keywords: ['Luxurious', 'Premium', 'Gifting'],
        liveSite: 'https://stg-single-page-checkout.netlify.app/kings-skincare/'
    },
    {
        id: 3,
        title: 'iHome Speaker Website',
        description: 'A modern one-page product website showcasing a Bluetooth speaker with a focus on clean design, smooth user experience, and clear product highlights such as wireless connectivity, portability, and high-quality sound.',
        type: 'One-Page Website',
        category: 'web',
        image: 'assets/img/ihomes.png',
        gallery: ['assets/img/ihomes_1.png'],
        techStack: ['HTML', 'CSS', 'JavaScript'],
        keywords: ['Modern', 'Sleek', 'Immersive'],
        liveSite: 'https://stg-single-page-checkout.netlify.app/ihome-speaker/'
    },
    {
        id: 4,
        slug: 'circlo',
        title: 'Circlo',
        description: 'A relationship-focused mobile app where people create private Circles for couples, friends, and families. I built the Flutter client and Laravel API foundation — theme, routing, auth shells, and Circle isolation — for a calm, private space with shared feed, chat, calendar, and type-specific modules.',
        type: 'Mobile App',
        category: 'mobile',
        image: 'assets/img/circlo.svg',
        gallery: ['assets/img/circlo.svg'],
        techStack: ['Flutter', 'Dart', 'Riverpod', 'Laravel', 'MySQL'],
        keywords: ['Mobile', 'Flutter', 'Circles'],
        liveSite: 'https://github.com/Ninixci4/Circlo',
        video: 'assets/video/circlo.mp4',
        screenshots: ['assets/img/circlo.svg']
    },
    {
        id: 5,
        title: 'Bidaboss Supplier Management System',
        description: 'A supplier-facing system inside Bidaboss for vendor onboarding, product listings, inventory, purchase orders, and status tracking — designed to keep supplier operations clear, consistent, and easier to manage alongside the main platform.',
        type: 'Web App',
        category: 'web',
        image: 'assets/img/Bidaboss.png',
        gallery: ['assets/img/bidaboss_1.png', 'assets/img/bidaboss_2.png'],
        techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'MySQL'],
        keywords: ['Suppliers', 'Operations', 'Dashboard'],
        liveSite: '#'
    },
    {
        id: 6,
        title: 'Bidaboss Main System',
        description: 'The core Bidaboss operations platform for catalog, orders, customers, and internal workflows. I focused on UI/UX and front-end so admins and staff can move through the main system with a cleaner hierarchy, stronger consistency, and faster day-to-day use.',
        type: 'Web App',
        category: 'web',
        image: 'assets/img/bidaboss_1.png',
        gallery: ['assets/img/Bidaboss.png', 'assets/img/bidaboss_2.png'],
        techStack: ['HTML', 'CSS', 'JavaScript', 'PHP', 'MySQL'],
        keywords: ['Operations', 'E-commerce', 'Admin'],
        liveSite: '#'
    },
    {
        id: 7,
        slug: 'quiz-mania',
        title: 'Quiz Mania',
        description: 'A mobile quiz app for taking timed multiple-choice quizzes, tracking scores, and reviewing results. Built as a compact, thumb-friendly experience with clear question flow, instant feedback, and a result report at the end of each round.',
        type: 'Mobile App',
        category: 'mobile',
        image: 'assets/img/quiz-mania.svg',
        gallery: ['assets/img/quiz-mania.svg'],
        techStack: ['Flutter', 'Dart', 'Firebase'],
        keywords: ['Mobile', 'Quiz', 'Learning'],
        liveSite: '#',
        video: 'assets/video/quiz-mania.mp4',
        screenshots: ['assets/img/quiz-mania.svg']
    },
    {
        id: 8,
        slug: 'bidaboss-app',
        title: 'Bidaboss Mobile App',
        description: 'The Bidaboss mobile app for browsing products, managing orders, and staying connected to the platform on the go. I worked on the UI/UX and front-end so shopping and order tracking feel consistent with the web experience, just sized for the phone.',
        type: 'Mobile App',
        category: 'mobile',
        image: 'assets/img/bidaboss_2.png',
        gallery: ['assets/img/bidaboss_2.png', 'assets/img/Bidaboss.png'],
        techStack: ['Flutter', 'Dart', 'REST API'],
        keywords: ['Mobile', 'E-commerce', 'Orders'],
        liveSite: '#',
        video: 'assets/video/bidaboss-app.mp4',
        screenshots: ['assets/img/bidaboss_2.png', 'assets/img/Bidaboss.png']
    }
];
